export const config = {
  name: process.env.NEXT_PUBLIC_AGENCY_NAME || "Nexus Digital",
  fullName: "Nexus Digital Marketing Agency",
  tagline: process.env.NEXT_PUBLIC_AGENCY_TAGLINE || "Best Digital Marketing & Website Development Agency in Gorakhpur, Uttar Pradesh, India",
  email: process.env.NEXT_PUBLIC_AGENCY_EMAIL || "nexusdigital.gkp@gmail.com",
  phone: process.env.NEXT_PUBLIC_AGENCY_PHONE || "+91-9696262007",
  phoneRaw: (process.env.NEXT_PUBLIC_AGENCY_PHONE || "+91-9696262007").replace(/[^0-9]/g, "").replace(/^91/, ""),
  whatsapp: process.env.NEXT_PUBLIC_AGENCY_WHATSAPP || "919696262007",
  address: process.env.NEXT_PUBLIC_AGENCY_ADDRESS || "Gorakhpur, Uttar Pradesh, India",
  city: "Gorakhpur",
  state: "Uttar Pradesh",
  country: "India",
  postalCode: "273001",
  website: process.env.NEXT_PUBLIC_AGENCY_WEBSITE || "https://thenexusdigital.in",
  logo: process.env.NEXT_PUBLIC_AGENCY_LOGO || "NexusDigital",
  shortName: process.env.NEXT_PUBLIC_AGENCY_SHORT_NAME || "Nexus",
  gmbName: process.env.NEXT_PUBLIC_AGENCY_GMB_NAME || "Nexus Digital Marketing Agency",
  gmbUrl: process.env.NEXT_PUBLIC_AGENCY_GMB_URL || "https://www.google.com/maps/place/Nexus+Digital+Marketing+Agency/@26.7780745,83.3677344,17z/data=!3m1!4b1!4m6!3m5!1s0x39914565c023e207:0xfb5a450c09bc064a!8m2!3d26.7780745!4d83.3703093!16s%2Fg%2F11ntr_kp4s",
  gmbRating: process.env.NEXT_PUBLIC_AGENCY_GMB_RATING || "5.0",
  gmbReviewCount: process.env.NEXT_PUBLIC_AGENCY_GMB_REVIEW_COUNT || "30",
  ogImage: `${process.env.NEXT_PUBLIC_AGENCY_WEBSITE || "https://thenexusdigital.in"}/og-image.jpg`,
  gstRate: Number(process.env.NEXT_PUBLIC_GST_RATE || 18),
  // Founder & Leadership Details
  founder: "Sahil Srivastava",
  founderRole: "Founder, SEO & Full-Stack Web Development Specialist",
  founderBio: "Driving business growth through technical SEO, high-converting Next.js / full-stack web development, and ROI-focused performance marketing across Gorakhpur, Uttar Pradesh, and India.",
  founderEmail: "user.kanxer@gmail.com",
  founderPhone: "+91-9696262007",
  founderPhoto: "/team/sahil.jpeg",
  founderSocials: {
    linkedin: "https://www.linkedin.com/in/kanxer",
    instagram: "https://www.instagram.com/__sahil.srivastava__",
    twitter: "https://x.com/itsSrivastava_",
    github: "https://github.com/kanXer",
    facebook: "https://www.facebook.com/sahil.srivastava.1004/",
  },
};
